Create website configuration and sidebar navigation.
Y-Shcheholskyy/graalpy.github.io pull request #11
Opened 2023-11-27 10:47 UTC by olyagpl

I have finished extending the exiting configuration and adding a sidebar navigation. 
Please checkout my branch and run locally to test changes. 
@Y-Shcheholskyy, can you please check why code snippets, with language specified, don't show up on docs pages (`docs-layout`)?
<img width="1511" alt="Screenshot 2023-11-27 at 16 54 46" src="https://github.com/Y-Shcheholskyy/graalpy.github.io/assets/31922163/79c67352-5714-4b3a-8738-fb6b14fc433a">

2023-11-27 14:08 UTC, bhoran commented on docs/examples/Examples.md
> -{% comment %}
Please retain this comment.

2023-11-27 14:12 UTC, bhoran commented on _config.yml
> +          [
Can't we read this from the data file instead of hard coding it into the config?

2023-11-27 16:07 UTC, olyagpl commented on _config.yml
> +          [
I used the common method. The sidebar navigation is created based on the _toc.html_ logic. The toc.html algorithm processes the `toc_group` lists  from _config.yml. Each docs header should contain the  `toc_group` value. The chain is: toc.html < config.yml <  toc_group value in docs headers.

2023-11-27 16:07 UTC, olyagpl commented on _config.yml
> +          [
I think we shouldn't over-invest  into changing the implementation details. As I understood, we want to have a sidebar navigation in docs.

2023-11-27 16:07 UTC, olyagpl commented on docs/examples/Examples.md
> -{% comment %}
Reverted in https://github.com/Y-Shcheholskyy/graalpy.github.io/pull/11/commits/17a033bcf9ace7b88592c8bc9e5fbe75c356b682

2023-11-27 16:14 UTC, Y-Shcheholskyy commented
> I have finished extending the exiting configuration and adding a sidebar navigation. Please checkout my branch and run locally to test changes. @Y-Shcheholskyy, can you please check why code snippets, with language specified, don't show up on docs pages (`docs-layout`)? <img alt="Screenshot 2023-11-27 at 16 54 46" width="1511" src="https://private-user-images.githubusercontent.com/31922163/285935008-79c67352-5714-4b3a-8738-fb6b14fc433a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMDE4NDIsIm5iZiI6MTcwMTEwMTU0MiwicGF0aCI6Ii8zMTkyMjE2My8yODU5MzUwMDgtNzljNjczNTItNTcxNC00YjNhLTg3MzgtZmI2YjE0ZmM0MzNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDE2MTIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNDk1ODgwZmVhY2IxM2FlMjgyZjBmNGUwNTNlODUwYTU0NGQzY2VkZjZiZGQ1MmI5MmRmOWU0ZmQwZDBkYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hEXgkB6PKsouxPqc4F-c00BnWWCaNvyT_RkQFXvZsCs">

I think the code snippets are there but have white text color and white background because I can see the "copy" buttons. I'll check

2023-11-27 16:37 UTC, Y-Shcheholskyy reviewed
From the point of view of the config implementation, everything is ok for me, there are quite a lot of inaccuracies in appearance, but I will fix all this in the next pull request.

2023-11-27 21:57 UTC, olyagpl commented
@Y-Shcheholskyy, why my pull request was closed instead of merged?

2023-11-27 22:14 UTC, Y-Shcheholskyy commented
> @Y-Shcheholskyy, why my pull request was closed instead of merged?

Why do you think it is closed? I have it open..

2023-11-28 09:58 UTC, bhoran commented on _config.yml
> +          [
This is really awkward. I really wanted to start this website from scratch instead of bringing over all the legacy coding from graal with its maintenance overhead.

2023-11-28 09:59 UTC, bhoran requested changes
Why is there a link_title in the frontmatter?

2023-11-29 13:42 UTC, Y-Shcheholskyy commented on _config.yml
> +          [
Don't worry, Bernard, I have found alt solution

2023-11-29 13:53 UTC, olyagpl commented
> Why is there a link_title in the frontmatter?

`link_title` is the menu item text you see in the sidebar navigation, if applying my(old) approach. 
`title` is for the search results.

2023-11-29 13:55 UTC, olyagpl commented on _config.yml
> +          [
To me the old site doesn't seem difficult than difficult. Yevhen has a simple solution afaik :)

2023-11-29 15:54 UTC, olyagpl commented
I'm declining this PR, as discussed at today's meeting. We will use the `jekyll-toc` plugin.

2023-11-29 15:54 UTC, closed without merging